export const backgroundImageIds = {
    "01d": "/backgroundImages/clear-day.png",
    "01n": "/backgroundImages/clear-night.png",
    "02d": "/backgroundImages/fewClouds-day.png",
    "02n": "/backgroundImages/fewClouds-night.png",
    "03d": "/backgroundImages/fewClouds-day.png",
    "03n": "/backgroundImages/fewClouds-night.png",
    "04d": "/backgroundImages/cloudy-day.png",
    "04n": "/backgroundImages/cloudy-night.png",
    "09d": "/backgroundImages/rain-day.png",
    "09n": "/backgroundImages/rain-night.png",
    "10d": "/backgroundImages/rain-day.png",
    "10n": "/backgroundImages/rain-night.png",
    "11d": "/backgroundImages/storm-day.png",
    "11n": "/backgroundImages/storm-night.png",
    "13d": "/backgroundImages/storm-day.png",
    "13n": "/backgroundImages/storm-night.png",

}

export const imageIconIds={
    "01d": "/weatherIcons/clear-day.png",
    "01n": "/weatherIcons/clear-night.png",
    "02d": "/weatherIcons/fewClouds-day.png",
    "02n": "/weatherIcons/fewClouds-night.png",
    "03d": "/weatherIcons/fewClouds-day.png",
    "03n": "/weatherIcons/fewClouds-night.png",
    "04d": "/weatherIcons/cloudy-day.png",
    "04n": "/weatherIcons/cloudy-night.png",
    "09d": "/weatherIcons/rain-day.png",
    "09n": "/weatherIcons/rain-night.png",
    "10d": "/weatherIcons/rain-day.png",
    "10n": "/weatherIcons/rain-night.png",
    "11d": "/weatherIcons/storm-day.png",
    "11n": "/weatherIcons/storm-night.png",
    "13d": "/weatherIcons/storm-day.png",
    "13n": "/weatherIcons/storm-night.png",
}